version: "3.3"

services:
  tribler-core:
    image: triblercore/triblercore:latest
    container_name: triblercore
    network_mode: "host"
    build: .
    volumes:
      - "~/.Tribler:/state"
      - "~/Downloads/TriblerDownloads:/downloads"
    environment:
      - CORE_API_PORT=20100
      - CORE_API_KEY=TEST
      - TORRENT_PORT=7000
      - TSTATEDIR=/state
