name: PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:

  # PR is Draft and PR is Ready
  pytest:
    uses: ./.github/workflows/pytest.yml
    with:
      python-version: 3.8
      matrix: '{"os": ["windows-latest"]}'

  guitest:
    uses: ./.github/workflows/guitest.yml
    with:
      python-version: 3.8
      matrix: '{"os": ["windows-latest"]}'

  scripttest:
    uses: ./.github/workflows/scripttest.yml
    with:
      python-version: 3.8

  coverage:
    uses: ./.github/workflows/coverage.yml
    with:
      python-version: 3.8

  # PR is Ready only
  pytest_nix:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/pytest.yml
    with:
      python-version: 3.8
      matrix: '{"os": ["macos-latest", "ubuntu-latest"]}'

  guitest_nix:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/guitest.yml
    with:
      python-version: 3.8
      matrix: '{"os": ["macos-latest", "ubuntu-latest"]}'

  ubuntu:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      upload: false
      os: ubuntu-20.04
      python-version: 3.8

  windows:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/build_windows.yml
    with:
      upload: false
      os: windows-latest
      python-version: 3.8

  mac:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/build_mac.yml
    with:
      upload: false
      os: macos-10.15
      python-version: 3.8

  documentation:
    if: ${{!github.event.pull_request.draft}}
    uses: ./.github/workflows/documentation.yml
    with:
      python-version: 3.8
