name: Publish Docker Image

on: workflow_dispatch
env:
  REF_NAME: ${{ github.ref_name }}

jobs:
  build-and-push-image-ghcr:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          submodules: 'true'
          fetch-tags: 'true'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tags
        id: git_tag_version
        run: |
          TAG=ghcr.io/tribler/tribler:$(git describe --tags)
          COMMIT=ghcr.io/tribler/tribler:$REF_NAME
          VERSION=ghcr.io/tribler/tribler:latest
          echo "TAG1=${TAG,,}" >> $GITHUB_ENV
          echo "TAG2=${COMMIT,,}" >> $GITHUB_ENV
          echo "TAG3=${VERSION,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/docker/build.Dockerfile
          push: true
          tags: |
            ${{ env.TAG1 }}
            ${{ env.TAG2 }}
            ${{ env.TAG3 }}
          build-args: |
            GIT_BRANCH=${{ github.ref_name }}
            GIT_REPO=https://github.com/${{ github.repository }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/tribler/tribler
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  build-and-push-image-dockerhub:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          submodules: 'true'
          fetch-tags: 'true'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Create tags
        id: git_tag_version
        run: |
          TAG=tribler/tribler:$(git describe --tags)
          COMMIT=tribler/tribler:$REF_NAME
          VERSION=tribler/tribler:latest
          echo "TAG1=${TAG,,}" >> $GITHUB_ENV
          echo "TAG2=${COMMIT,,}" >> $GITHUB_ENV
          echo "TAG3=${VERSION,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/docker/build.Dockerfile
          push: true
          tags: |
            ${{ env.TAG1 }}
            ${{ env.TAG2 }}
            ${{ env.TAG3 }}
          build-args: |
            GIT_BRANCH=${{ github.ref_name }}
            GIT_REPO=https://github.com/${{ github.repository }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/tribler/tribler
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
