name: Binaries

on:
  pull_request:

jobs:
  ubuntu:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      upload: false
      os: ubuntu-20.04
