name: GUI test

on:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.8' ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-test.txt

      - name: Install xvfb dependencies
        run: |
          sudo apt install xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
        # For more information see: https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions

      - name: Run GUI tests
        run: |
          xvfb-run  pytest ./src/tribler/gui --guitests -v --randomly-seed=1
