name: Pytest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8']
        os: [macos-10.15, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Libsodium
        if: matrix.os == 'windows-latest'
        run: |
          C:\msys64\usr\bin\wget.exe -q https://download.libsodium.org/libsodium/releases/libsodium-1.0.17-msvc.zip
          7z x libsodium-1.0.17-msvc.zip
          copy ./x64/Release/v141/dynamic/libsodium.dll C:\Windows\system32\

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-test.txt

      - name: Run Pytest
        run: |
          pytest ./src/tribler/core

      - name: Run Tunnels Tests
        run: |
          pytest ./src/tribler/core/components/tunnel/tests/test_full_session --tunneltests
