# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Upload Coverage

on:
  workflow_run:
    workflows: [ 'Coverage' ]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage_report
      - name: Upload codacy-coverage-report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml
